package ai.pdfparser;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.imageio.ImageIO;

import java.awt.image.BufferedImage;

import org.apache.pdfbox.Loader;
import org.apache.pdfbox.cos.COSName;
import org.apache.pdfbox.io.MemoryUsageSetting;
import org.apache.pdfbox.multipdf.PDFMergerUtility;
import org.apache.pdfbox.multipdf.PageExtractor;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageTree;
import org.apache.pdfbox.pdmodel.PDResources;
import org.apache.pdfbox.pdmodel.graphics.PDXObject;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;
import org.apache.pdfbox.text.PDFTextStripper;

public class App 
{
    // public static void main( String[] args ) throws IOException
    // {
    //     App myPDFReader = new App();
    //     myPDFReader.outputPageByFromPDF("C:\\Users\\jhe\\Desktop\\Scholarships NI.pdf",
    //                                     new String[]{"Abstract Submission Number 202",
    //                                     "Abstract Submission Number 1547",
    //                                     "Abstract Submission Number 2014",
    //                                     "Abstract Submission Number 2289",
    //                                     "Abstract Submission Number 2782",
    //                                     "Abstract Submission Number 3180",
    //                                     "Abstract Submission Number 274",
    //                                     "Abstract Submission Number 559",
    //                                     "Abstract Submission Number 677",
    //                                     "Abstract Submission Number 682",
    //                                     "Abstract Submission Number 706",
    //                                     "Abstract Submission Number 966",
    //                                     "Abstract Submission Number 989",
    //                                     "Abstract Submission Number 1045",
    //                                     "Abstract Submission Number 1068",
    //                                     "Abstract Submission Number 1234",
    //                                     "Abstract Submission Number 1235",
    //                                     "Abstract Submission Number 1455",
    //                                     "Abstract Submission Number 1527",
    //                                     "Abstract Submission Number 1660",
    //                                     "Abstract Submission Number 1795",
    //                                     "Abstract Submission Number 1839",
    //                                     "Abstract Submission Number 2160",
    //                                     "Abstract Submission Number 2177",
    //                                     "Abstract Submission Number 2601",
    //                                     "Abstract Submission Number 2671",
    //                                     "Abstract Submission Number 2836",
    //                                     "Abstract Submission Number 2913",
    //                                     "Abstract Submission Number 3033",
    //                                     "Abstract Submission Number 3143",
    //                                     "Abstract Submission Number 3204",
    //                                     "Abstract Submission Number 273",
    //                                     "Abstract Submission Number 288",
    //                                     "Abstract Submission Number 365",
    //                                     "Abstract Submission Number 367",
    //                                     "Abstract Submission Number 460",
    //                                     "Abstract Submission Number 613",
    //                                     "Abstract Submission Number 643",
    //                                     "Abstract Submission Number 663",
    //                                     "Abstract Submission Number 797",
    //                                     "Abstract Submission Number 1007",
    //                                     "Abstract Submission Number 1088",
    //                                     "Abstract Submission Number 1279",
    //                                     "Abstract Submission Number 1529",
    //                                     "Abstract Submission Number 1533",
    //                                     "Abstract Submission Number 1587",
    //                                     "Abstract Submission Number 1608",
    //                                     "Abstract Submission Number 1650",
    //                                     "Abstract Submission Number 1685",
    //                                     "Abstract Submission Number 1727",
    //                                     "Abstract Submission Number 1739",
    //                                     "Abstract Submission Number 1804",
    //                                     "Abstract Submission Number 2305",
    //                                     "Abstract Submission Number 2307",
    //                                     "Abstract Submission Number 2359",
    //                                     "Abstract Submission Number 2392",
    //                                     "Abstract Submission Number 2422",
    //                                     "Abstract Submission Number 2465",
    //                                     "Abstract Submission Number 2659",
    //                                     "Abstract Submission Number 2926",
    //                                     "Abstract Submission Number 3010",
    //                                     "Abstract Submission Number 3131",
    //                                     "Abstract Submission Number 3140",
    //                                     "Abstract Submission Number 3165",
    //                                     "Abstract Submission Number 164",
    //                                     "Abstract Submission Number 234",
    //                                     "Abstract Submission Number 284",
    //                                     "Abstract Submission Number 290",
    //                                     "Abstract Submission Number 354",
    //                                     "Abstract Submission Number 433",
    //                                     "Abstract Submission Number 618",
    //                                     "Abstract Submission Number 624",
    //                                     "Abstract Submission Number 659",
    //                                     "Abstract Submission Number 713",
    //                                     "Abstract Submission Number 742",
    //                                     "Abstract Submission Number 801",
    //                                     "Abstract Submission Number 826",
    //                                     "Abstract Submission Number 946",
    //                                     "Abstract Submission Number 1103",
    //                                     "Abstract Submission Number 1216",
    //                                     "Abstract Submission Number 1306",
    //                                     "Abstract Submission Number 1359",
    //                                     "Abstract Submission Number 1367",
    //                                     "Abstract Submission Number 1390",
    //                                     "Abstract Submission Number 1414",
    //                                     "Abstract Submission Number 1583",
    //                                     "Abstract Submission Number 1588",
    //                                     "Abstract Submission Number 1752",
    //                                     "Abstract Submission Number 1805",
    //                                     "Abstract Submission Number 1814",
    //                                     "Abstract Submission Number 1864",
    //                                     "Abstract Submission Number 1902",
    //                                     "Abstract Submission Number 2003",
    //                                     "Abstract Submission Number 2013",
    //                                     "Abstract Submission Number 2155",
    //                                     "Abstract Submission Number 2212",
    //                                     "Abstract Submission Number 2266",
    //                                     "Abstract Submission Number 2292",
    //                                     "Abstract Submission Number 2401",
    //                                     "Abstract Submission Number 2514",
    //                                     "Abstract Submission Number 2669",
    //                                     "Abstract Submission Number 2725",
    //                                     "Abstract Submission Number 2742",
    //                                     "Abstract Submission Number 2796",
    //                                     "Abstract Submission Number 2864",
    //                                     "Abstract Submission Number 2929",
    //                                     "Abstract Submission Number 3081",
    //                                     "Abstract Submission Number 3122",
    //                                     "Abstract Submission Number 840",
    //                                     "Abstract Submission Number 943",
    //                                     "Abstract Submission Number 1077",
    //                                     "Abstract Submission Number 1311",
    //                                     "Abstract Submission Number 1702",
    //                                     "Abstract Submission Number 1744",
    //                                     "Abstract Submission Number 1806",
    //                                     "Abstract Submission Number 1995",
    //                                     "Abstract Submission Number 1999",
    //                                     "Abstract Submission Number 2082",
    //                                     "Abstract Submission Number 2093",
    //                                     "Abstract Submission Number 2176",
    //                                     "Abstract Submission Number 2180",
    //                                     "Abstract Submission Number 2182",
    //                                     "Abstract Submission Number 2688",
    //                                     "Abstract Submission Number 2710",
    //                                     "Abstract Submission Number 2935",
    //                                     "Abstract Submission Number 3172",
    //                                     "Abstract Submission Number 2494",
    //                                     "Abstract Submission Number 1774",
    //                                     "Abstract Submission Number 2059",
    //                                     "Abstract Submission Number 2159",
    //                                     "Abstract Submission Number 1296",
    //                                     "Abstract Submission Number 1576",
    //                                     "Abstract Submission Number 2228",
    //                                     "Abstract Submission Number 2501",
    //                                     "Abstract Submission Number 440",
    //                                     "Abstract Submission Number 685",
    //                                     "Abstract Submission Number 734",
    //                                     "Abstract Submission Number 1079",
    //                                     "Abstract Submission Number 1165",
    //                                     "Abstract Submission Number 1474",
    //                                     "Abstract Submission Number 1546",
    //                                     "Abstract Submission Number 1604",
    //                                     "Abstract Submission Number 1620",
    //                                     "Abstract Submission Number 1666",
    //                                     "Abstract Submission Number 2262",
    //                                     "Abstract Submission Number 2278",
    //                                     "Abstract Submission Number 2490",
    //                                     "Abstract Submission Number 2979",
    //                                     "Abstract Submission Number 2992",
    //                                     "Abstract Submission Number 3156",
    //                                     "Abstract Submission Number 183",
    //                                     "Abstract Submission Number 361",
    //                                     "Abstract Submission Number 848",
    //                                     "Abstract Submission Number 1690",
    //                                     "Abstract Submission Number 2075",
    //                                     "Abstract Submission Number 2110",
    //                                     "Abstract Submission Number 2133",
    //                                     "Abstract Submission Number 2856",
    //                                     "Abstract Submission Number 327",
    //                                     "Abstract Submission Number 1307",
    //                                     "Abstract Submission Number 1394",
    //                                     "Abstract Submission Number 1494",
    //                                     "Abstract Submission Number 1960",
    //                                     "Abstract Submission Number 1977",
    //                                     "Abstract Submission Number 2074",
    //                                     "Abstract Submission Number 3167",
    //                                     "Abstract Submission Number 248",
    //                                     "Abstract Submission Number 324",
    //                                     "Abstract Submission Number 480",
    //                                     "Abstract Submission Number 830",
    //                                     "Abstract Submission Number 972",
    //                                     "Abstract Submission Number 1243",
    //                                     "Abstract Submission Number 1747",
    //                                     "Abstract Submission Number 2581",
    //                                     "Abstract Submission Number 2633",
    //                                     "Abstract Submission Number 2756",
    //                                     "Abstract Submission Number 2877",
    //                                     "Abstract Submission Number 2882",
    //                                     "Abstract Submission Number 219",
    //                                     "Abstract Submission Number 351",
    //                                     "Abstract Submission Number 803",
    //                                     "Abstract Submission Number 895",
    //                                     "Abstract Submission Number 793",
    //                                     "Abstract Submission Number 1025",
    //                                     "Abstract Submission Number 1039",
    //                                     "Abstract Submission Number 1298",
    //                                     "Abstract Submission Number 3046",
    //                                     "Abstract Submission Number 3098",
    //                                     "Abstract Submission Number 282",
    //                                     "Abstract Submission Number 992",
    //                                     "Abstract Submission Number 1623",
    //                                     "Abstract Submission Number 1646",
    //                                     "Abstract Submission Number 1682",
    //                                     "Abstract Submission Number 2134",
    //                                     "Abstract Submission Number 2368",
    //                                     "Abstract Submission Number 2980",
    //                                     "Abstract Submission Number 209",
    //                                     "Abstract Submission Number 308",
    //                                     "Abstract Submission Number 360",
    //                                     "Abstract Submission Number 506",
    //                                     "Abstract Submission Number 807",
    //                                     "Abstract Submission Number 1069",
    //                                     "Abstract Submission Number 1637",
    //                                     "Abstract Submission Number 1708",
    //                                     "Abstract Submission Number 1809",
    //                                     "Abstract Submission Number 1825",
    //                                     "Abstract Submission Number 1956",
    //                                     "Abstract Submission Number 2122",
    //                                     "Abstract Submission Number 2284",
    //                                     "Abstract Submission Number 2338",
    //                                     "Abstract Submission Number 2343",
    //                                     "Abstract Submission Number 2393",
    //                                     "Abstract Submission Number 2504",
    //                                     "Abstract Submission Number 2931",
    //                                     "Abstract Submission Number 3003",
    //                                     "Abstract Submission Number 525",
    //                                     "Abstract Submission Number 592",
    //                                     "Abstract Submission Number 593",
    //                                     "Abstract Submission Number 604",
    //                                     "Abstract Submission Number 813",
    //                                     "Abstract Submission Number 1073",
    //                                     "Abstract Submission Number 1075",
    //                                     "Abstract Submission Number 1310",
    //                                     "Abstract Submission Number 1706",
    //                                     "Abstract Submission Number 1904",
    //                                     "Abstract Submission Number 1979",
    //                                     "Abstract Submission Number 2092",
    //                                     "Abstract Submission Number 2727",
    //                                     "Abstract Submission Number 2728",
    //                                     "Abstract Submission Number 2900",
    //                                     "Abstract Submission Number 3062",
    //                                     "Abstract Submission Number 1179",
    //                                     "Abstract Submission Number 1610",
    //                                     "Abstract Submission Number 1846",
    //                                     "Abstract Submission Number 3035",
    //                                     "Abstract Submission Number 279",
    //                                     "Abstract Submission Number 1765",
    //                                     "Abstract Submission Number 1929",
    //                                     "Abstract Submission Number 2781",
    //                                     "Abstract Submission Number 3037",
    //                                     "Abstract Submission Number 3133",
    //                                     "Abstract Submission Number 213",
    //                                     "Abstract Submission Number 497",
    //                                     "Abstract Submission Number 703",
    //                                     "Abstract Submission Number 809",
    //                                     "Abstract Submission Number 893",
    //                                     "Abstract Submission Number 1351",
    //                                     "Abstract Submission Number 1886",
    //                                     "Abstract Submission Number 2058",
    //                                     "Abstract Submission Number 2774",
    //                                     "Abstract Submission Number 2892",
    //                                     "Abstract Submission Number 116",
    //                                     "Abstract Submission Number 223",
    //                                     "Abstract Submission Number 535",
    //                                     "Abstract Submission Number 620",
    //                                     "Abstract Submission Number 823",
    //                                     "Abstract Submission Number 835",
    //                                     "Abstract Submission Number 1064",
    //                                     "Abstract Submission Number 1548",
    //                                     "Abstract Submission Number 1893",
    //                                     "Abstract Submission Number 2032",
    //                                     "Abstract Submission Number 2324",
    //                                     "Abstract Submission Number 2421",
    //                                     "Abstract Submission Number 2690",
    //                                     "Abstract Submission Number 2704",
    //                                     "Abstract Submission Number 2713"                                        
    //                                     }, "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures");
    // }

    public static void main( String[] args ) throws IOException {
        App myPDFReader = new App();
        myPDFReader.mergeScholarshipAppsAndLetter(new String[]{"C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\116.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\164.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\183.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\202.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\209.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\213.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\219.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\223.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\234.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\248.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\273.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\274.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\279.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\282.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\284.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\288.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\290.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\308.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\324.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\327.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\351.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\354.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\360.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\361.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\365.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\367.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\433.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\440.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\460.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\480.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\497.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\506.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\525.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\535.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\559.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\592.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\593.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\604.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\613.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\618.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\620.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\624.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\643.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\659.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\663.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\677.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\682.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\685.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\703.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\706.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\713.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\734.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\742.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\793.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\797.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\801.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\803.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\807.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\809.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\813.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\823.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\826.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\830.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\835.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\840.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\848.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\893.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\895.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\943.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\946.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\966.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\972.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\989.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\992.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1007.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1025.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1039.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1045.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1064.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1068.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1069.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1073.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1075.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1077.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1079.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1088.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1103.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1165.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1179.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1216.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1234.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1235.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1243.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1279.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1296.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1298.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1306.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1307.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1310.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1311.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1351.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1359.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1367.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1390.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1394.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1414.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1455.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1474.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1494.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1527.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1529.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1533.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1546.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1547.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1548.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1576.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1583.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1587.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1588.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1604.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1608.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1610.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1620.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1623.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1637.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1646.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1650.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1660.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1666.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1682.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1685.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1690.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1702.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1706.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1708.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1727.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1739.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1744.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1747.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1752.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1765.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1774.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1795.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1804.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1805.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1806.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1809.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1814.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1825.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1839.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1846.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1864.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1886.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1893.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1902.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1904.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1929.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1956.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1960.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1977.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1979.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1995.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\1999.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2003.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2013.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2014.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2032.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2058.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2059.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2074.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2075.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2082.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2092.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2093.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2110.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2122.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2133.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2134.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2155.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2159.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2160.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2176.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2177.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2180.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2182.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2212.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2228.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2262.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2266.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2278.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2284.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2289.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2292.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2305.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2307.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2324.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2338.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2343.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2359.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2368.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2392.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2393.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2401.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2421.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2422.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2465.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2490.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2494.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2501.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2504.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2514.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2581.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2601.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2633.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2659.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2669.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2671.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2688.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2690.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2704.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2710.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2713.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2725.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2727.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2728.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2742.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2756.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2774.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2781.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2782.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2796.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2836.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2856.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2864.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2877.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2882.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2892.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2900.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2913.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2926.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2929.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2931.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2935.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2979.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2980.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\2992.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3003.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3010.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3033.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3035.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3037.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3046.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3062.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3081.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3098.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3122.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3131.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3133.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3140.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3143.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3156.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3165.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3167.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3172.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3180.pdf",
        "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\_ExtractedFigures\\3204.pdf"
        }, 
                                                    new String[]{"G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\116.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\164.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\183.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\202.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\209.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\213.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\219.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\223.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\234.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\248.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\273.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\274.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\279.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\282.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\284.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\288.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\290.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\308.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\324.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\327.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\351.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\354.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\360.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\361.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\365.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\367.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\433.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\440.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\460.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\480.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\497.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\506.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\525.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\535.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\559.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\592.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\593.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\604.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\613.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\618.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\620.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\624.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\643.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\659.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\663.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\677.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\682.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\685.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\703.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\706.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\713.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\734.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\742.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\793.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\797.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\801.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\803.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\807.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\809.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\813.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\823.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\826.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\830.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\835.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\840.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\848.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\893.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\895.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\943.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\946.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\966.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\972.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\989.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\992.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1007.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1025.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1039.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1045.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1064.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1068.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1069.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1073.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1075.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1077.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1079.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1088.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1103.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1165.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1179.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1216.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1234.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1235.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1243.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1279.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1296.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1298.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1306.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1307.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1310.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1311.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1351.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1359.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1367.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1390.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1394.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1414.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1455.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1474.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1494.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1527.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1529.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1533.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1546.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1547.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1548.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1576.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1583.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1587.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1588.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1604.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1608.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1610.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1620.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1623.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1637.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1646.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1650.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1660.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1666.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1682.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1685.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1690.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1702.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1706.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1708.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1727.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1739.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1744.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1747.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1752.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1765.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1774.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1795.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1804.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1805.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1806.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1809.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1814.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1825.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1839.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1846.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1864.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1886.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1893.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1902.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1904.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1929.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1956.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1960.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1977.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1979.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1995.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\1999.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2003.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2013.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2014.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2032.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2058.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2059.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2074.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2075.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2082.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2092.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2093.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2110.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2122.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2133.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2134.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2155.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2159.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2160.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2176.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2177.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2180.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2182.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2212.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2228.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2262.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2266.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2278.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2284.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2289.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2292.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2305.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2307.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2324.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2338.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2343.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2359.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2368.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2392.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2393.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2401.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2421.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2422.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2465.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2490.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2494.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2501.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2504.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2514.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2581.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2601.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2633.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2659.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2669.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2671.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2688.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2690.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2704.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2710.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2713.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2725.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2727.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2728.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2742.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2756.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2774.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2781.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2782.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2796.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2836.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2856.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2864.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2877.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2882.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2892.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2900.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2913.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2926.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2929.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2931.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2935.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2979.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2980.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\2992.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3003.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3010.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3033.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3035.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3037.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3046.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3062.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3081.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3098.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3122.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3131.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3133.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3140.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3143.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3156.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3165.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3167.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3172.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3180.pdf",
                                                    "G:\\CROI\\31st CROI 2024\\Scholarships\\Letter of Recommendations For Script\\3204.pdf",
                                                    },
                                                    "C:\\Users\\jhe\\Desktop\\New folder\\output.pdf");
    }
    // {
    //     App myPDFReader = new App();

    private PDDocument destination; 

    /**
     * @param scholarshipAppsPath
     * @param scholarshipLettersPath
     * @param depositFolderPath
     * @throws IOException
     */
    public void mergeScholarshipAppsAndLetter(String[] scholarshipAppsPath, String[] scholarshipLettersPath, String depositFolderPath) throws IOException {
        String outputPath = "C:\\Users\\jhe\\OneDrive - IAS-USA\\_Programming Projects\\my_pdfparser\\Output.pdf";
        PDDocument outputPDF = Loader.loadPDF(new File(outputPath));

        PDFMergerUtility pdfMerger = new PDFMergerUtility();
        pdfMerger.setDestinationFileName(depositFolderPath);

        for (int i = 0; i < scholarshipAppsPath.length; i++) {
            PDDocument schapp = Loader.loadPDF(new File(scholarshipAppsPath[i]));
            PDDocument schlet = Loader.loadPDF(new File(scholarshipLettersPath[i]));
            pdfMerger.appendDocument(outputPDF, schapp);
            pdfMerger.appendDocument(outputPDF, schlet);
        }
        outputPDF.save(depositFolderPath);
    }

    public void outputPageByFromPDF(String pdfFilePath, String[] abstractNumberTargets, String depositFolderPath) throws IOException {
        PDDocument document = null;
        try {
            document = Loader.loadPDF(new File(pdfFilePath));
            Map<String, Integer> mapTargetsToPageNumber = getMapAbstractNumberToPageNumber(document, abstractNumberTargets);
            for (Map.Entry<String,Integer> entry : mapTargetsToPageNumber.entrySet()) {
                //TODO: Troubleshoot why this is off by 1
                PageExtractor pageExtractor = new PageExtractor(document, entry.getValue()+1, entry.getValue()+1);
                System.out.println(entry.getValue());
                PDDocument singlePage = pageExtractor.extract();
                String filename = depositFolderPath + "\\" + entry.getKey().replace("AbstractSubmissionNumber", "") + ".pdf";
                singlePage.save(filename);
            }
        } finally {
            if (document != null) {
                document.close();
            }
        }
    }

    public void outputFiguresFromPDF(String pdfFilePath, String[] abstractNumberTargets, String depositFolderPath) throws IOException {
        PDDocument document = null;
        try {
            document = Loader.loadPDF(new File(pdfFilePath));
            Map<String, Integer> mapTargetsToPageNumber = getMapAbstractNumberToPageNumber(document, abstractNumberTargets);
            for (Map.Entry<String,Integer> entry : mapTargetsToPageNumber.entrySet()) {
                BufferedImage figure = getImageOnAfterPage(document, entry.getValue());
                if (figure != null) {
                    File outputFile = new File(depositFolderPath + "\\" + entry.getKey().replace("AbstractSubmissionNumber", "") + ".png");
                    ImageIO.write(figure, "png", outputFile);
                } else {
                    System.out.println("Error: " + entry.getKey() + " - could not find figure");
                }
            }
        } finally {
            if (document != null) {
                document.close();
            }
        }
    }

    private Map<String, Integer> getMapAbstractNumberToPageNumber(PDDocument document, String[] abstractNumberTargets) throws IOException {
        Map<String, Integer> map = new HashMap<>();
        List<String> cleanedAbstractNumberTargets = getCleanedAbstractNumberTargets(abstractNumberTargets);
        for (int i = 0; i < document.getNumberOfPages(); i++) {
            String pageText = getPageText(document, i+1);
            int indexFoundInTargets = pageContainsAbstractNumber(pageText, cleanedAbstractNumberTargets);
            if (indexFoundInTargets > -1) map.put(cleanedAbstractNumberTargets.get(indexFoundInTargets), i);
        }
        return map;
    }

    /**
     * Cleaned meaning each target string has their spaces removed so the check later has no need to worry
     * about newlines and end whitespaces.
     * @param abstractNumberTargets
     * @return
     */
    private List<String> getCleanedAbstractNumberTargets(String[] abstractNumberTargets) {
        List<String> cleaned = new ArrayList<>();
        for (int i = 0; i < abstractNumberTargets.length; i++) {
            cleaned.add(abstractNumberTargets[i].replace(" ", "").trim());
        }
        return cleaned;
    }

    //Tested - Works!
    private BufferedImage getImageOnAfterPage(PDDocument document, int page) {
        BufferedImage buffImage = null;
        PDPageTree pageTree = document.getPages();

        for (int i = page; i < document.getNumberOfPages(); i++) {
            PDPage curPage = pageTree.get(i);
            PDResources curPageResources = curPage.getResources();
            for (COSName cosName : curPageResources.getXObjectNames()) {
                try {
                    PDXObject xObject = curPageResources.getXObject(cosName);
                    if (xObject instanceof PDImageXObject) {
                        PDImageXObject pdImage = (PDImageXObject) xObject;
                        buffImage = pdImage.getImage();
                        break;
                    }
                } catch (IOException ex) {

                }
            }
            if (buffImage != null) break;
        }

        return buffImage;
    }

    //Tested - Works
    private String getPageText(PDDocument document, int page) throws IOException {
        PDFTextStripper textStripper = new PDFTextStripper();
        textStripper.setStartPage(page);
        textStripper.setEndPage(page);
        textStripper.setSortByPosition(true);
        String pageText = textStripper.getText(document);
        return pageText;
    }

    //Tested - Works
    private int pageContainsAbstractNumber(String pageText, List<String> targetAbstractNumbers) {
        String[] splitted = pageText.split("\n");
        for (int i = 0; i < splitted.length; i++) {
            String curText = splitted[i].replace(" ", "").trim();
            // String targetTextTrim = targetAbstractNumbers.replace(" ", "").trim();
            int curTextHasTarget = targetAbstractNumbers.indexOf(curText);
            if (curTextHasTarget > -1) {
                return curTextHasTarget;
            }
        }
        return -1;
    }
}
